export const LOGIN = "LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const ACTIVATE_ACCOUNT = "ACTIVATE_ACCOUNT";


export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";

export const TOGGLE_FAV_PRODUCT = "TOGGLE_FAV_PRODUCT";
export const SET_USER_LOGGED = "SET_USER_LOGGED";
